# Build stage
FROM golang:1.24 AS builder

WORKDIR /app

# Copy go.mod and go.sum first
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the code
COPY . .

# Build the Go binary
RUN go build -o main ./cmd

# Final stage
FROM debian:bookworm-slim

WORKDIR /app

# Copy binary
COPY --from=builder /app/main .

# Copy SQL queries (and other assets if needed)
COPY --from=builder /app/internal/infrastructure/databases/queries ./internal/infrastructure/databases/queries

CMD ["./main"]